name: CD

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Login GHCR
      - name: Login to GHCR
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      # ===== BACKEND =====
      - name: Build Backend
        run: |
          docker build -t ghcr.io/${{ github.repository }}-backend:latest ./backend

      - name: Push Backend
        run: |
          docker push ghcr.io/${{ github.repository }}-backend:latest

      # ===== FRONTEND =====
      - name: Build Frontend
        run: |
          docker build -t ghcr.io/${{ github.repository }}-frontend:latest ./frontend

      - name: Push Frontend
        run: |
          docker push ghcr.io/${{ github.repository }}-frontend:latest

      # ===== DEPLOY SERVER =====
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /root
            bash deploy.sh